# Generated by Django 4.0.1 on 2022-01-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('remitente', models.CharField(max_length=100)),
                ('especies', models.CharField(max_length=30)),
                ('raza', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField()),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_llegada', models.DateTimeField()),
                ('edad', models.IntegerField(null=True)),
                ('vacunas', models.ManyToManyField(blank=True, to='main.Vacuna')),
            ],
        ),
    ]
