# Generated by Django 4.0.1 on 2022-01-22 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='especies',
            new_name='especie',
        ),
    ]
